 - hosts: host-sample
   tasks:
   - name: Get CPU usage
     shell: "echo $(uptime| rev | awk '{print $1\" \"$2\" \"$3 }'|rev)"
     register: cpuload

   - name: Get CPU core
     shell: "nproc"
     register: cpucores

   - name: Get Public IP
     uri:
      url: "http://ipinfo.io/ip"
      method: "GET"
      http_agent: "curl/7.58.0"
      return_content: yes
     register: publicip

   - name: Get Root System Size
     shell: "df -h /|tail -1|awk '{print $2}'"
     register: rootsize

   - name: Get Root System Usage
     shell: "df -h /|tail -1|awk '{print $3}'"
     register: rootusage

   - name: Get Root System Percentage
     shell: "df -h /|tail -1| rev|awk '{print $2}'|rev"
     register: rootpercentage

   - name: Get Ram Size
     shell: "free -m| grep Mem|awk '{print $2}'"
     register: ramsize

   - name: Get Ram Usage
     shell: "free -m| grep Mem|awk '{print $3}'"
     register: ramusage

   - name: Get Swap Size
     shell: "free -m| grep Swap|awk '{print $2}'"
     register: swapsize

   - name: Get Swap Usage
     shell: "free -m| grep Swap|awk '{print $3}'"
     register: swapusage

   - name: Set Usage facts
     set_fact:
       cpu_load: "{{ cpuload.stdout_lines[0] }}"
       cpu_cores: "{{ cpucores.stdout_lines[0]}}"
       public_ip: "{{ publicip.content.split()[0] }}"
       root_usage: "{{ rootusage.stdout_lines[0] }}"
       root_size: "{{ rootsize.stdout_lines[0] }}"
       ram_size: "{{ ramsize.stdout_lines[0] }}"
       ram_usage: "{{ ramusage.stdout_lines[0] }}"
       swap_size: "{{ swapsize.stdout_lines[0] }}"
       swap_usage: "{{ swapusage.stdout_lines[0] }}"
       root_percentage: "{{ rootpercentage.stdout_lines[0] }}"

   - name: Host-Sample Server Usage
     debug:
      msg: 
        - "Hostname: {{ ansible_hostname }}"
        - "CPU: {{ ansible_processor[2] }}"
        - "CPU Core: {{ cpu_cores }}"
        - "CPU Load : {{ cpu_load }}"
        - "Ram Size (In MB): {{ ram_size }}"
        - "Ram Used (In MB): {{ ram_usage }}"
        - "Ram Used (In %): {{ (ram_usage|int / ram_size|int * 100)| int  }}"
        - "Swap Size (In MB) : {{ swap_size }}"
        - "Swap Used (In MB): {{ swap_usage }}"
        - "Swap Used (In %): {{ (swap_usage|int / (swap_size|int + 1)|int * 100)| int }}"
        - "System : {{ ansible_mounts[0].mount }}"
        - "PartitionID : {{ ansible_mounts[0].device }}"
        - "Storage Size : {{ root_size }}"
        - "Storage Used : {{ root_usage }}"
        - "Storage Used (In %): {{ root_percentage }}"
        - "PublicIP : {{ public_ip }}"
